name: /home/wangshuai/softwares/SpecHLA/spechla_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - amply=0.1.5=pyhd8ed1ab_0
  - arpack=3.8.0=nompi_h0baa96a_101
  - biopython=1.79=py38h497a2fe_1
  - bowtie2=2.4.5=py38hfbc8389_2
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=he2f9439_0
  - coin-or-clp=1.17.6=h256e9bb_3
  - coin-or-osi=0.108.7=h3b589db_0
  - coin-or-utils=2.11.6=h573740c_0
  - coincbc=2.10.8=0_metapackage
  - curl=7.83.1=h7bff187_0
  - docutils=0.18.1=py38h578d9bd_1
  - htslib=1.15.1=h9753748_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=14_linux64_openblas
  - libcblas=3.9.0=14_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=14_linux64_openblas
  - liblapacke=3.9.0=14_linux64_openblas
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libzlib=1.2.11=h166bdaf_1014
  - longshot=0.4.5=hc4ca7c3_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.3=h27087fc_1
  - numpy=1.22.3=py38h99721a1_2
  - openssl=1.1.1s=h166bdaf_0
  - pandas=1.2.5=py38h295c915_0
  - pbmm2=1.9.0=h9ee0642_0
  - perl=5.32.1=2_h7f98852_perl5
  - pip=22.0.4=pyhd8ed1ab_0
  - pulp=2.6.0=py38h578d9bd_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysam=0.19.0=py38h8bf8b8d_0
  - python=3.8.12=ha38a3c6_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2022.1=py38h06a4308_0
  - pyvcf=0.6.8=py38h32f6830_1002
  - readline=8.1=h46c0cb4_0
  - scipy=1.8.0=py38h56a6a73_1
  - setuptools=62.3.2=py38h578d9bd_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=h4ff8645_0
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=h8a70e8d_1
prefix: /home/wangshuai/softwares/SpecHLA/spechla_env
